### ISSUE TITLE
be careful !

### ISSUE THREAD

**Issue by sdds1978** [EugeneSunrise/MixSoft#4]
Be careful, they have already detected it today and they received it. The cheat is very useful, I hope you publish a new update. I also left you a star.

**Comment by EugeneSunrise** [comment]
What do you mean bro? Ban on 5E or Matchmaking?if you mean 5e, then you need to change the variables in the project, change assmbly and need vmprotect or themida, enigma

**Comment by sdds1978** [comment]
I used this hack in csgo, and played casual matchmaking, which is what I
always play. and it doesn't take long for them to VAC me and I have to
close the hack, and verify the integrity of the csgo game files. I have
tried several times and the same thing always happens. I like the hack to
change skins mainly, which is the only thing that interests me, but they
always take me out of the game. I don't know what programs are the ones you
mention above, am I missing something?

**Comment by EugeneSunrise** [comment]
Bro, I have the same problem as you, but I'm not sure that the reason is cheats and so on, I get this error even when I play without software, moreover, my friends have been playing with Mixsoft for the past two years and during this time they never had this error, also I will throw off a couple of articles that can help you solve this error

https://www.dexerto.com/csgo/fix-vac-authentication-errors-csgo-steam-1349762/
https://digistatement.com/counter-strike-global-offensive-vac-authentication-error-how-to-fix-it-in-2021/
https://appuals.com/how-to-fix-the-vac-authentication-error/
